#Nom du workFlow
name: Hello word

#Levenment declencheur
on: [push]

#Difinir des taches (jobs) a excecuter
jobs:
  say_hello: #Nom de job
    run-on: ubuntu-latest #Difinir le runner (machine virtuelle) utilisée : Ubuntu

    steps: #Suite d'etapes a excecuter
      - name: Print Hello #Nom detape
        run: echo "Bonjour depuis GitHub Actions"